In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.24.0


In [9]:
a = np.array([1,2,3])
print(a)
print(a.shape)
print(a.dtype)
print(a.ndim)
print(a.size)
print(a.itemsize)  

[1 2 3]
(3,)
int64
1
3
8


In [11]:
b = a * np.array([2,0,2])
print(b)

[2 0 6]


In [25]:
l = [1,2,3]
a = np.array([1,2,3])

print(l)
print(a)

l.append(4)
l = l + [5]

# a.append(4) Doesn't work
a = a + np.array([4])
print("--")

print(l)
print(a)

l = l * 2
a = a * 2

print("--")
print(l)
print(a)


[1, 2, 3]
[1 2 3]
--
[1, 2, 3, 4, 5]
[5 6 7]
--
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[10 12 14]


In [31]:
l1 = [1,2,3]
l2 = [4,5,6]

a1 = np.array([1,2,3])
a2 = np.array([4,5,6])

# dot product
dot = 0
for i in range(len(l1)):
    dot += l1[i] * l2[i]

print(dot)

dot = np.dot(a1,a2)
print(dot)

sum1 = a1 * a2
dot = np.sum(sum1)
print(dot)

dot = a1 @ a2
print(dot)

32
32
32
32


In [32]:
a = np.array([1,2,3])
print(a.shape)

(3,)


In [44]:
a = np.array([[1,2],[3,4],[5,6]])
print(a.shape)
print(a[0][0])
print(a[0,0])
print(a[:,0])
print(a[0,:])
print(a.T)


(3, 2)
1
1
[1 3 5]
[1 2]
[[1 3 5]
 [2 4 6]]


In [48]:
a = np.array([[1,2],[3,4]])
print(np.linalg.inv(a))
print(np.linalg.det(a))
print(np.diag(a))

c = np.diag(a)
print(np.diag(c))

[[-2.   1. ]
 [ 1.5 -0.5]]
-2.0000000000000004
[1 4]
[[1 0]
 [0 4]]


In [50]:
b = a[0,1]
print(b)



2


In [55]:
a = np.array([[1,2,3,4],[5,6,7,8]])
b = a[0,1:3]

print(b)
b = a[:,0]
print(b)

[2 3]
[1 5]


In [56]:
print(a[a > 2])

[3 4 5 6 7 8]


In [58]:
b = np.where(a > 2, a, -1)
print(b)

[[-1 -1  3  4]
 [ 5  6  7  8]]


In [59]:
a = np.array([10,19,30,41,50,61])
print(a)

[10 19 30 41 50 61]


In [60]:
b = [1,3,5]
print(a[b])

[19 41 61]


In [61]:
even = np.argwhere(a%2==0).flatten()
print(a[even])

[10 30 50]


In [68]:
a = np.arange(1,7)
print(a)
print(a.shape)
b = a.reshape((2,3))
print(b)
print(b.shape)

[1 2 3 4 5 6]
(6,)
[[1 2 3]
 [4 5 6]]
(2, 3)


In [72]:
b = a[np.newaxis,:]
print(b)
print(b.shape)
print()
b = a[:, np.newaxis]
print(b)
print(b.shape)


[[1 2 3 4 5 6]]
(1, 6)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(6, 1)


In [79]:
a = np.array([[2,3],[4,5]])
print(a)
print()

b = np.array([[7,8]])
c = np.concatenate((a,b))
print(c)
print()
c = np.concatenate((a,b), axis=None)
print(c)
print()
c = np.concatenate((a,b.T), axis=1)
print(c)

[[2 3]
 [4 5]]

[[2 3]
 [4 5]
 [7 8]]

[2 3 4 5 7 8]

[[2 3 7]
 [4 5 8]]


In [81]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

print(np.hstack((a,b)))
print(np.vstack((a,b)))


[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]


In [83]:
x = np.array([[1,2,3],[4,5,6],[1,2,3],[4,5,6]])
a = np.array([1,0,1])
y = x + a
print(y)

[[2 2 4]
 [5 5 7]
 [2 2 4]
 [5 5 7]]


In [91]:
a = np.array([[7,8,9,10,11,12,13],[17,18,19,20,21,22,23]])
print(a)

print()
print(a.sum(axis=None))

print()
print(a.sum(axis=0))

print()
print(a.sum(axis=1))
print(np.sum(a,axis=1))

[[ 7  8  9 10 11 12 13]
 [17 18 19 20 21 22 23]]

210

[24 26 28 30 32 34 36]

[ 70 140]
[ 70 140]


In [94]:
x = np.array([1.0,2.0])
print(x)
print(x.dtype)

print()
x = np.array([1.0,2.0], dtype=np.int64)
print(x)
print(x.dtype)

[1. 2.]
float64

[1 2]
int64


In [97]:
a = np.array([1,2,3])
b = a

b[0] = 42
print(a)
print(b)

print()

a = np.array([1,2,3])
b = a.copy()

b[0] = 42
print(a)
print(b)

[42  2  3]
[42  2  3]

[1 2 3]
[42  2  3]


In [109]:
a = np.zeros((2,3))
print(a)
print()

a = np.ones((2,3))
print(a)
print(a.dtype)
print()

a = np.full((2,3), 5.0)
print(a)
print(a.dtype)
print()

a = np.eye(3)
print(a)
print()

a = np.arange(20)
print(a)
print()

a = np.linspace(0,10,5)
print(a)


[[0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1.]
 [1. 1. 1.]]
float64

[[5. 5. 5.]
 [5. 5. 5.]]
float64

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

[ 0.   2.5  5.   7.5 10. ]


In [126]:
a = np.random.random((3,2)) # 0-1
print(a)
print()

a = np.random.randn(3,2) # normal/Gausian
print(a)
print()

a = np.random.randn(1000)
print(a.mean(), a.var())
print()

a = np.random.randint(3,10, size=(3,3))
print(a)
print()

a = np.random.choice(5,size=10)
print(a)
print()

a = np.random.choice([-8,-7,-6],size=10)
print(a)

[[0.55158005 0.21455874]
 [0.01993548 0.78745399]
 [0.3005897  0.17652748]]

[[-0.64981018  0.7084001 ]
 [-1.08222124  0.12486256]
 [ 0.40585306 -1.50806891]]

-0.04822908866054738 0.929878813328073

[[3 7 6]
 [9 3 3]
 [7 7 3]]

[3 3 3 3 2 3 4 1 1 4]

[-6 -8 -7 -6 -7 -6 -7 -7 -7 -8]


In [138]:
a = np.array([[1,2],[3,4]])

eigenvalues, eigenvectors = np.linalg.eig(a)
print(eigenvalues)
print(eigenvectors) # Column vector
print()

# e_vec * e_val = A * e_vec
b = eigenvectors[:,0] * eigenvalues[0]
print(b)
print()

c = a @ eigenvectors[:,0]
print(c)

# print(c==b)
print(np.allclose(b,c))

[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]

[ 0.30697009 -0.21062466]

[ 0.30697009 -0.21062466]
True


In [141]:
A = np.array([[1,1],[1.5,4.0]])
b = np.array([2200,5050])

x = np.linalg.inv(A).dot(b)
print(x)

x = np.linalg.solve(A,b)
print(x)

[1500.  700.]
[1500.  700.]
